### PR TITLE
Use string_tree module in favor of deprecated string_builder module of Gleam

### PR DESCRIPTION
**Pull request by diemogebhardt**
Since release 1.6.0 of Gleam, [string_builder](https://hexdocs.pm/gleam_stdlib/gleam/string_builder.html) has been deprecated in favor of [string_tree](https://hexdocs.pm/gleam_stdlib/gleam/string_tree.html).

This PR:
- introduces **BREAKING CHANGES**:
  - Reasoning is that matcha is feature complete and stable. Whoever depends on [string_builder](https://hexdocs.pm/gleam_stdlib/gleam/string_builder.html) just sticks with the current version and does not upgrade to the next/latest versions including this change. Reduces maintenance overhead for deprecated functionality – for example, in the case of a command line option.
    - Version 1.0.0 doesn't sound too bad, does it? ;)
    - In case you agree, this might need to be documented in README.md (including version/release numbers)
  - [Updates gleam dependency (gleam_stdlib from version 0.38.0 to 0.43.0)](https://github.com/michaeljones/matcha/commit/e6d919bbda007790d92f3abe705ef36994cc96aa)
  - Uses [StringTree](https://hexdocs.pm/gleam_stdlib/gleam/string_tree.html) instead of [StringBuilder](https://hexdocs.pm/gleam_stdlib/gleam/string_builder.html) types in [Refactor to use string_tree module instead of deprecated string_builder module of gleam](https://github.com/michaeljones/matcha/commit/276f380860fd6a054ff4898f75a2a9de48cd7526)
  - [Renames public instances of render_builder to render_tree](https://github.com/michaeljones/matcha/commit/3765cf19bf42153f64279c225c8372381fe43773)
    - In case the "builder" naming pattern should be kept, this commit just needs to be reverted.
  - [Renames private instances of render to tree](https://github.com/michaeljones/matcha/commit/cf8bdfd7f703492d44ee7bc3910ff90b8ccec8b3)
    - In case the "builder" naming pattern should be kept, this commit just needs to be reverted.
  - Updates links to lustre and nakai in `README.md`
    - nakai just [released a new version](https://github.com/aslilac/nakai/releases/tag/v1.1.0), adding support for the gleam `string_tree` module but dropping support for the gleam `string_builder` module completely.
    - lustre has an [open PR](https://github.com/lustre-labs/lustre/pull/215) (by me) to add support for the gleam `string_tree` module in addition to the gleam `string_builder` module.
- introduces minor gleam related improvements:
  - [Formats gleam code](https://github.com/michaeljones/matcha/commit/37322479dba16d49228daf85de843a5a9484589a)
  - [Reorders gleam imports](https://github.com/michaeljones/matcha/commit/ea1d86e251ff275926f88a250e221bee3565d049)
  - [Ignores gleam build folder (git)](https://github.com/michaeljones/matcha/commit/06bcfdc3076f2a7f0a267f17b64d5b65e7398045)

Going through the individual commits should make it easier for you to review all changes in digestible chunks.

All tests are passing. Generated gleam code by a "from source" build of this branch has been deployed by a few projects to production already. :)

### CODE REVIEW

**Comment by michaeljones** [comment]
Thank you very much for this. Looks great. I appreciate the clear commit separation for the different aspects of the change.

It looks like our CI hasn't been run for a while and needs updating so I'll push some commits to try to do that but otherwise it looks great and I'd be happy merge and I'm grateful for your efforts!

**Comment by michaeljones** [comment]
The further changes are presumably associated with newer versions of the rust toolchain and compiler warnings, etc.

**Comment by michaeljones** [comment]
You make a fair point about going 1.0. Let's see how this set of changes settles in and then we can go 1.0 (though I realise there is a risk I'll forget about it entirely!)

**Comment by diemogebhardt** [comment]
> Thank you very much for this. Looks great. I appreciate the clear commit separation for the different aspects of the change.

Oh, awesome – didn't expect for this to get merged that quick. Happy to contribute whenever I can. And thank you, for creating this in the first place! :)

> You make a fair point about going 1.0. Let's see how this set of changes settles in and then we can go 1.0

Yeah, going `1.0.0` feels like a big step. I see it from the perspective of communicating the breaking changes of a dependency, less than a set of features. SemVer is great for that. When upgrading matcha from version `0.*.*` to `0.*.*` I would just yolo it without thinking. Seeing the version increase from `0.*.*` to `1.*.*` I would definitely check out the changelog first in order to decide whether I want to spend the next couple of hours refactoring my codebase.

Even though off-topic in the context of this PR: is there a specific set of features that you would like to see for `1.0.0`?

> (though I realise there is a risk I'll forget about it entirely!)

Let me create an issue (https://github.com/michaeljones/matcha/issues/32) as a reminder and you decide whatever to do with it... ;)

**Pull request merged**
