### PR TITLE
Add explicit target during build

### LINKED ISSUE #23: Fix macOS aarch64 release
There's been a [bug issue](https://github.com/gleam-lang/gleam/issues/1626) opened in the Gleam repository about wrong CPU type in macOS release. Supposedly specifying `default: true` in the `actions-rs/toolchain` is not enough for it to be the picked up when running on the amd64 runner on Github Actions. The release Github Actions workflow in this repository follows the same pattern as the Gleam workflow.

I don't have an Apple M1 device to test this, can someone confirm if it's a problem in the latest [matcha release](https://github.com/michaeljones/matcha/releases/tag/0.13.0)? If so, maybe a [patch](https://github.com/gleam-lang/gleam/pull/1627/files) to the github actions release workflow is needed.

To test it out, please download the [macos `arm64` release](https://github.com/michaeljones/matcha/releases/download/0.13.0/matcha-0.13.0-macos-arm64.tar.gz), extract, and provide what the `file` command returns for it:
```
file matcha
```

### PR DESCRIPTION
**Pull request by michallepicki**
to fix macOS aarch64 (arm64) release to be truly aarch64

Closes #23

### CODE REVIEW

**Comment by michaeljones** [comment]
Thanks so much for keeping an eye out on these things. I'm not sure knowledgeable on the platform builds & distribution. 

Are you happy if this is merged as is? Or should we ask someone to double check the result? Or does that come after merging? :)

**Comment by michallepicki** [comment]
I'm pretty sure it will work but now that you're asking I can at least push a tag on my fork and see if the binary reports itself correctly now. I'll get back to you later today

**Comment by michaeljones** [comment]
Kind of you. Sorry for introducing doubt :)

**Comment by michallepicki** [comment]
[Looking good](https://github.com/michallepicki/matcha/releases/tag/4.2.0), the arm64 release now reports itself as:
```
$ file matcha
matcha: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
```

**Comment by michaeljones** [comment]
Ace, so we merge this and tag a new release or re-run the workflow for the last release somehow? Sorry for the questions. I'm a bit out of the loop.

**Comment by michallepicki** [comment]
> a new release or re-run the workflow for the last release somehow

🤔 I didn't think about that but I think re-running a workflow would still run the action without the fix. So the tag either needs to be moved to a newer commit with this merged, or the project needs a new release. TBH I'm not sure this fix alone needs a new release, I think waiting for more features/fixes on main is fine, because the old "arm64" release should work on M1 MacBooks thanks to Rosetta

**Comment by michaeljones** [comment]
I'm happy to merge and make a new release. I appreciate you fixing it up.

**Pull request merged**
